### PR TITLE
Product deployment step logging

### PR DESCRIPTION
**Pull request by valevalorin**

### CODE REVIEW

**Comment by msawka** [comment]
* Do you need the [ui_url](https://github.com/OpenAperture/product_deployment_orchestrator/blob/pds_logging/lib/product_deployment_orchestrator/configuration.ex#L61)?  If so, make sure the config application name is correct, not overseer ([here](https://github.com/OpenAperture/product_deployment_orchestrator/blob/pds_logging/lib/product_deployment_orchestrator/configuration.ex#L47) as well)
* Let's remove the [inspect](https://github.com/OpenAperture/product_deployment_orchestrator/blob/pds_logging/lib/product_deployment_orchestrator/dispatcher.ex#L68-L69)
* In the [dispatcher](https://github.com/OpenAperture/product_deployment_orchestrator/blob/pds_logging/lib/product_deployment_orchestrator/dispatcher.ex#L78-L85), can you generate a SystemEvent when in exception cases, similar to [overseer](https://github.com/OpenAperture/overseer/blob/master/lib/overseer/dispatcher.ex#L90-L101)
* Update or delete the [comments](https://github.com/OpenAperture/product_deployment_orchestrator/blob/pds_logging/lib/product_deployment_orchestrator/product_deployment_fsm.ex#L2-L17)
* In the FSM, can you setup the logging so that each FSM has a uuid and prepends that to any logs that are generated, similar to the [WorkflowFSM[(https://github.com/OpenAperture/workflow_orchestrator/blob/master/lib/workflow_orchestrator/workflow_fsm.ex#L308)?  Makes it easier for debugging
* Do we need this [case statement](https://github.com/OpenAperture/product_deployment_orchestrator/blob/pds_logging/lib/product_deployment_orchestrator/product_deployment_fsm.ex#L139-L153)?  Couldn't it be handled simply by returning {:reply, :in_progress, String.to_atom(step.type), state_data}, similar to [this](https://github.com/OpenAperture/workflow_orchestrator/blob/master/lib/workflow_orchestrator/workflow_fsm.ex#L243)?
* Rather than use a [case statement](https://github.com/OpenAperture/product_deployment_orchestrator/blob/pds_logging/lib/product_deployment_orchestrator/product_deployment_fsm.ex#L161), could we use method pattern matching in the state data, something like build_deploy(_current_state, _from, {step_status: in_progress} = state_data), and then build_deploy(_current_state, _from, state_data)?
* [Here](https://github.com/OpenAperture/product_deployment_orchestrator/blob/pds_logging/lib/product_deployment_orchestrator/product_deployment_fsm.ex#L198-L199), [manager_api](https://github.com/OpenAperture/manager_api/blob/master/lib/openaperture_manager_api/response.ex#L71) already has a method for doing this.

**Comment by valevalorin** [comment]
Valid values for "type" field of event?

**Comment by msawka** [comment]
:unhandled_exception

**Comment by valevalorin** [comment]
For the FSM ID, is that ID tied to the FSM or the workflow/deployment/whatever it's processing?

**Comment by valevalorin** [comment]
>Rather than use a case statement, could we use method pattern matching in the state data,    something like build_deploy(_current_state, _from, {step_status: in_progress} = state_data), and then build_deploy(_current_state, _from, state_data)?

That data isn't easily accessible, because you want the step status of the current step which could be at any level of the plan tree.

I could try to pull the current step out of the tree and put it in state_data somewhere if you want though.

**Comment by msawka** [comment]
If it's tricky from the top-level, we can leave it; but can we have the method call 2 child methods so we can have a clean separation of the logic?

**Comment by valevalorin** [comment]
So, yeah, figured out how to deconstruct the state_data for a match. What about the ID?

**Pull request merged**
